# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '明日方舟.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import (QApplication, QPushButton,
                      QThread,QMutex,pyqtSignal)

global game_num
global state
global run_time
qmut_1 = QMutex() # 创建线程锁
# 继承QThread
class Thread_1(QThread):  # 线程1
    def __init__(self):
        super().__init__()

    def run(self):
        qmut_1.lock() # 加锁
        if state == 1:
            for game_num in range(1,100):
                self.AK_start()
                if run_time == 2:
                    self.AK_start_game_main()
                if run_time == 122:
                    self.AK_over()
                if run_time == 127:
                    run_time = 0
                    game_num = game_num - 1
                run_time = run_time + 1
            qmut_1.unlock() # 解锁
        elif state == 2:
            for game_num in range(1, 100):
                self.AK_start()
                if run_time == 2:
                    self.AK_start_game_move()
                if run_time == 202:
                    self.AK_over()
                if run_time == 207:
                    run_time = 0
                    game_num = game_num - 1
                run_time = run_time + 1
            qmut_1.unlock() # 解锁
        elif state == 3:
            for game_num in range(1, 100):
                self.AK_start()
                if run_time == 2:
                    self.AK_start_game_battle()
                if run_time == 902:
                    self.AK_over()
                if run_time == 907:
                    run_time=0
                    game_num=game_num-1
                run_time = run_time + 1
            qmut_1.unlock() # 解锁
global game_num

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("明日方舟_Breeezer_X")
        MainWindow.resize(728, 1029)
        MainWindow.setMaximumSize(QtCore.QSize(728, 1029))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(50, 30, 171, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.currentIndexChanged.connect(self.AK_CB)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 920, 131, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.AK_OK)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 90, 99, 30))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 90, 113, 28))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.textChanged.connect(self.AK_edit)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 920, 131, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.AK_Stop)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(390, 40, 155, 25))
        self.radioButton.setObjectName("radioButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(510, 90, 113, 28))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setReadOnly(True)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 90, 99, 21))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "明日方舟_Breeezer_X"))
        self.comboBox.setItemText(0, _translate("MainWindow", "夏活副本"))
        self.comboBox.setItemText(1, _translate("MainWindow", "剿灭副本"))
        self.comboBox.setItemText(2, _translate("MainWindow", "主线副本"))
        self.pushButton.setText(_translate("MainWindow", "确定"))
        self.label.setText(_translate("MainWindow", "次数:"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.lineEdit_2.setText(_translate("MainWindow", "0"))
        self.pushButton_2.setText(_translate("MainWindow", "取消战斗"))
        self.radioButton.setText(_translate("MainWindow", "战斗中"))
        self.label_2.setText(_translate("MainWindow", "剩余次数:"))

    def AK_start(self):#开始
        os.system(r'G:\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe connect 127.0.0.1:7555')
        os.system(r'G:\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe shell input tap 1425 826')
    def AK_over(self):#结束游戏
        os.system(r'G:\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe shell input tap 725 262')
    def AK_start_game_main(self):#主线
        os.system(r'G:\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe shell input tap 1375 785')
    def AK_start_game_move(self):#夏活动
        os.system(r'G:\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe shell input tap 1375 785')
    def AK_start_game_battle(self):#剿灭
        os.system(r'G:\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe shell input tap 1375 785')

    def AK_OK(self):
        global game_num
        global state
        if self.radioButton.isChecked() == False:
            if self.comboBox.currentText() == "主线副本":
                state=1
                self.thread_1 = Thread_1()  # 创建线程
                self.thread_1.start()  # 开始线程
            if self.comboBox.currentText() == "剿灭副本":
                state=2
                self.thread_1 = Thread_1()  # 创建线程
                self.thread_1.start()  # 开始线程
            if self.comboBox.currentText() == "夏活副本":
                state=3
                self.thread_1 = Thread_1()  # 创建线程
                self.thread_1.start()  # 开始线程
        else:
            print('None')
    def AK_Stop(self):
        self.radioButton.setChecked(False)
        print('stop')
    def AK_edit(self,text):
        print('输入的内容:' + text)
        global game_num
        game_num=int(text)
    def AK_CB(self,i):
        #标签用来显示选中的文本
        print(self.comboBox.currentText())
